-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Windows\Documents\Practicas MATLAB\Rampa\rampa\rampa.vhd
-- Created: 2022-05-08 12:08:10
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001
-- Target subsystem base rate: 0.001
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: rampa
-- Source Path: rampa/rampa
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.rampa_pkg.ALL;

ENTITY rampa IS
  PORT( clk                               :   IN    std_logic;
        in1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En10
        out_rsvd                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En10
        );
END rampa;


ARCHITECTURE rtl OF rampa IS

  -- Component Declarations
  COMPONENT Discrete_FIR_Filter
    PORT( clk                             :   IN    std_logic;
          Discrete_FIR_Filter_in          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En29
          Discrete_FIR_Filter_out         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En10
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Discrete_FIR_Filter
    USE ENTITY work.Discrete_FIR_Filter(rtl);

  -- Signals
  SIGNAL in1_signed                       : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Delay_out1                       : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Delay1_out1                      : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Gain1_cast                       : signed(16 DOWNTO 0);  -- sfix17_En10
  SIGNAL Gain1_cast_1                     : signed(16 DOWNTO 0);  -- sfix17_En10
  SIGNAL Gain1_out1                       : signed(31 DOWNTO 0);  -- sfix32_En25
  SIGNAL Sum_out1                         : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Gain_out1                        : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL Sum1_add_cast                    : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Sum1_add_cast_1                  : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Sum1_out1                        : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Gain4_out1                       : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL Gain3_out1                       : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL Sum3_add_cast                    : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Sum3_add_cast_1                  : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Sum3_out1                        : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Gain2_out1                       : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Sum2_add_cast                    : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Sum2_out1                        : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Delay2_reg                       : vector_of_signed16(0 TO 34);  -- sfix16 [35]
  SIGNAL Delay2_out1                      : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Sum4_out1                        : signed(15 DOWNTO 0);  -- sfix16_En10
  SIGNAL Gain5_out1                       : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL Discrete_FIR_Filter_out1         : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Discrete_FIR_Filter : Discrete_FIR_Filter
    PORT MAP( clk => clk,
              Discrete_FIR_Filter_in => std_logic_vector(Gain5_out1),  -- sfix32_En29
              Discrete_FIR_Filter_out => Discrete_FIR_Filter_out1  -- sfix16_En10
              );

  in1_signed <= signed(in1);

  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      Delay1_out1 <= Delay_out1;
    END IF;
  END PROCESS Delay1_process;


  Gain1_cast <= resize(Delay1_out1, 17);
  Gain1_cast_1 <=  - (Gain1_cast);
  Gain1_out1 <= Gain1_cast_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      Delay_out1 <= Sum_out1;
    END IF;
  END PROCESS Delay_process;


  Gain_out1 <= resize(Delay_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  Sum1_add_cast <= Gain_out1(28 DOWNTO 13);
  Sum1_add_cast_1 <= Gain1_out1(30 DOWNTO 15);
  Sum1_out1 <= Sum1_add_cast + Sum1_add_cast_1;

  Sum_out1 <= in1_signed + Sum1_out1;

  Gain4_out1 <= to_signed(16#4600#, 16) * Sum_out1;

  -- CSD Encoding (32768) : 1000000000000000; Cost (Adders) = 0
  Gain3_out1 <=  - (resize(Delay_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32));

  Sum3_add_cast <= Gain4_out1(25 DOWNTO 10);
  Sum3_add_cast_1 <= Gain3_out1(29 DOWNTO 14);
  Sum3_out1 <= Sum3_add_cast + Sum3_add_cast_1;

  Gain2_out1 <= to_signed(-16#43E3#, 16) * Delay_out1;

  Sum2_add_cast <= Gain2_out1(24 DOWNTO 9);
  Sum2_out1 <= Sum_out1 + Sum2_add_cast;

  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      Delay2_reg(0) <= Sum2_out1;
      Delay2_reg(1 TO 34) <= Delay2_reg(0 TO 33);
    END IF;
  END PROCESS Delay2_process;

  Delay2_out1 <= Delay2_reg(34);

  Sum4_out1 <= Sum3_out1 + Delay2_out1;

  Gain5_out1 <= to_signed(16#7507#, 16) * Sum4_out1;

  out_rsvd <= Discrete_FIR_Filter_out1;

END rtl;

